[package]
name = "gnome-robots"
version = "50.0.0"
edition = "2024"
rust-version = "1.93"

[dependencies]
gtk = { package = "gtk4", version = "0.11", features = ["gnome_50"] }
adw = { package = "libadwaita", version = "0.9", features = ["v1_9"] }
gly = { package = "libglycin-rebind", version = "0.2" }
gly_gtk = { package = "libglycin-gtk4-rebind", version = "0.2" }
gettext-rs = { version = "0.8", features = ["gettext-system"] }
rand = "0.10"
async-channel = "2.1.1"
serde = { version = "1.0.217", features = ["derive"] }
