[package]
name = "gnome-robots"
version = "41.1.0"
edition = "2021"

[dependencies]
gtk = { package = "gtk4", version = "0.9", features = ["gnome_45"] }
adw = { package = "libadwaita", version = "0.7", features = ["v1_4"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
librsvg = "2.58.2"
regex = "1"
rand = "0.8"
async-channel = "2.1.1"
