.\" Copyright (C) 2007 Sven Arvidsson <sa@whiz.se>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH gnome-robots 6 "2007\-06\-07" "GNOME"
.SH NAME
Robots \- Based on classic BSD Robots
.SH SYNOPSIS
.B gnome-robots
.RI [ OPTION... ]
.SH DESCRIPTION
.B gnome-robots
is a game where you try and avoid a band of marauding
robots which are, for no adequately explained reason, trying to kill
you. It is based on the text-based robots game which can be found on a
number of UNIX systems.
.SH OPTIONS
.TP
.B \-c, --config=NAME
Set game configuration. Choose from "robots2", "robots2 easy", "classic
robots", "robots with safe teleport" and "nightmare".
.TP
.B \-x, \-\-x=X
Initial window position
.TP
.B \-y, \-\-y=Y
Initial window position
.P
This program also accepts the standard GNOME and GTK options.
.SH AUTHORS
.B gnome-robots
was written by Mark Rae <m.rae@inpharmatica.co.uk>.
.P
This manual page was written by Sven Arvidsson <sa@whiz.se>,
for the Debian project (but may be used by others).
.SH SEE ALSO
.BR "gtk-options" (7),
.BR "gnome-options" (7)
.P
The online documentation available through the program's
.I Help
menu.
